name: Docs & Spec
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  validate-openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install spectral
        run: |
          npm i -g @stoplight/spectral-cli
      - name: Lint OpenAPI
        run: |
          if [ -f openapi/openapi.yaml ]; then spectral lint openapi/openapi.yaml; else echo "No openapi spec"; fi
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link check (basic)
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --exclude-mail --exclude "https://localhost" "docs/**/*.md"
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
